### ISSUE TITLE
kasmVNC Module

### ISSUE THREAD

**Issue by bpmct** [coder/modules#1]
Create a module that installs kasmvnc if it doesn't exist and starts it. 

## Must have

- [x] coder_app
- [x] coder_script (https://github.com/coder/coder/pull/9584)

## Nice to have

- [x] Variable to specify kasmvnc version
- [ ] Variable to skip install (assumes it's already in the image)
- [ ] Variable for path of kasmvnc (e.g. in home dir?)

## References

- A generic script I made to install kasmVNC on an Ubuntu Focal VM: https://gist.github.com/bpmct/4e51d7092089f278c91f53e344749b6c
- KasmVNC Kubernetes templates: https://github.com/sharkymark/v2-templates

**Comment by matifali** [comment]
Looks like adding kasmVNC on top of any image is not that easy.

**Comment by bpmct** [comment]
Adding into this sprint as we have some customers asking about this. I wonder if we can support it in a relatively generic way, or if we need docs or example images.

**Comment by matifali** [comment]
@bpmct #24 Should work on all Debian and Ubuntu-based workspaces. Feel free to redo it.
