### ISSUE TITLE
vault-github: user is not part of required org

### ISSUE THREAD

**Issue by kleberbaum** [coder/modules#108]
**Module:** vault-github
**Coder Version:** 2.4.0
**Vault Version:** 1.15.3
**Issue:** Error with `ghu_` prefixed GitHub App token during workspace startup; `ghp_` personal access tokens work fine.

**Error Message on Workspace Startup:** 
```
Error authenticating: Error making API request.
URL: PUT http://192.168.1.105:8200/v1/auth/github/login
Code: 500. Errors:
* user is not part of required org
```

**Configuration:**
- Installed and configured the vault-github module in a Coder template.
- Engaged GitHub authentication and established GitHub organization in Vault settings.

**Discovery:**
- Authentication with GitHub App tokens (`ghu_` prefix) fails upon workspace initialization.
- Authentication using personal access tokens (`ghp_` prefix) performs correctly.

**Steps to Reproduce:**
1. Set up the vault-github module in Coder template.
   ```terraform
   module "vault" {
     source     = "https://registry.coder.com/modules/vault-github"
     agent_id   = coder_agent.dev.id
     vault_addr = "http://192.168.1.105:8200"
     coder_github_auth_id   = "primary-github"
   }
   ```
2. Activated GitHub authentication and set the GitHub organization in Vault.
   ```bash
   vault auth enable github
   vault write auth/github/config organization=photonq-org
   ```
3. Encountered an error when starting the workspace using a GitHub App token.
   ```bash
   vault login -method=github token=ghu_MyGitHubAppAccessToken
   ```
4. Successfully logged in with a personal access token.
   ```bash
   vault login -method=github token=ghp_MyPersonalAccessToken
   ```

**Question:**
Is additional configuration required within HashiCorp Vault to enable authentication using GitHub App tokens (`ghu_` prefix) as they produce an error stating the user is not part of the required organization?

**Comment by bpmct** [comment]
cc @matifali

**Comment by matifali** [comment]
Closing in favour of #175
