### ISSUE TITLE
Allow basename of url to be added to custom path in the Git-Clone module 

### ISSUE THREAD

**Issue by Conor-Behard333** [coder/modules#120]
I am cloning a repo with the git-clone module.

```HCL
module "git-clone" {
 source = "https://registry.coder.com/modules/git-clone"
 agent_id = coder_agent.main.id
 url = https://git-domain/test-repo
 path = "/home/coder/workspace" 
}
```

Instead of the code being cloned to /home/coder/workspace/ I want it to be cloned to /home/coder/workspace/test-repo.

Possible solution would be to change the tf here: https://github.com/coder/modules/blob/main/git-clone/main.tf

Maybe creating an optional var `enable_basename` and if set to true does something like this:
`CLONE_PATH : var.path != "" ?  join("/", [var.path, basename(var.url)]) : join("/", ["~", basename(var.url)]),`

**Comment by matifali** [comment]
@Conor-Behard333 Could you just change path to `path = "/home/coder/workspace/test-repo"` as a workaround? 
`

**Comment by Conor-Behard333** [comment]
Unfortunately not as with the template I've made the user can add their own git repo so it needs to be named dynamically

**Comment by matifali** [comment]
feel free to send a PR

**Comment by Conor-Behard333** [comment]
@matifali got one for review
