### ISSUE TITLE
 Git Clone Error: "base_dir" is not expected here.

### ISSUE THREAD

**Issue by pxPP** [coder/modules#137]
On the latest version 1.0.2 of Git Clone we have the problem that after a while when stopping a workspace - build, deploy and start work - we get the following error message:

`An argument named "base_dir" is not expected here.`

Our configuration is as follows:

```hcl
module "git-clone" {
    source   = "registry.coder.com/modules/git-clone/coder"
    version  = "1.0.2"
    agent_id = coder_agent.main.id
    url      = "${local.gitRepo}"
    base_dir = "/workspace"
}
```

By updating the template and recreating the workspace, it works again for a while until the error reappears.

**Comment by matifali** [comment]
This should have been resolved by now. There was an issue with the registry.coder.com web server not handling tags correctly.
cc: @mafredri
