### ISSUE TITLE
Hardcoded IDE versions in locals should be refactored into variables

### ISSUE THREAD

**Issue by asvoboda** [coder/modules#145]
Eg, in https://github.com/coder/modules/blob/acab6437bca3201d33604ddd1add550ca6d8c5b4/jetbrains-gateway/main.tf#L62 the cal-versioned dates should be in a a variable and then included in the local diffs so that downstream template operators can control which versions appear as linked the in UI.

**Comment by matifali** [comment]
Thank you @asvoboda. I agree that we should allow users to override the versions. We are open to contributions if you want to submit a PR for this.
