### ISSUE TITLE
Git commit signing Permission denied

### ISSUE THREAD

**Issue by TheZoker** [coder/modules#149]
Hi there,

I use the [Git commit signing](https://registry.coder.com/modules/git-commit-signing?tab=variables) module and every time my workspace starts, I get this error:
```sh
sh: 26: cannot create /home/User/.ssh/git-commit-signing/coder.pub: Permission denied
sh: 30: cannot create /home/User/.ssh/git-commit-signing/coder: Permission denied
```

It seems the keys have the following permission:
```
-r-------- 1 User User 388 Feb  7 23:33 coder
-r-------- 1 User User 82 Feb  7 23:33 coder.pub
```

Any idea how to fix this? Thanks!

**Comment by matifali** [comment]
cc: @phorcys420

**Comment by phorcys420** [comment]
hey, it seems that I didn't write the script properly because it sets `400` (`-r--------`) permission to both of the keys when they should be more permissive.

I will publish a fix ASAP (expect a week of delay at most).
