### ISSUE TITLE
Jetbrains Gateway: Ouptuts

### ISSUE THREAD

**Issue by djarbz** [coder/modules#188]
I am having issues referencing the outputs of the Jetbrains Gateway module.

Abbreviated section of my template.
```
resource "docker_container" "workspace" {
  env        = [
    "CODER_AGENT_TOKEN=${coder_agent.main.token}",
    "PROJECT_DIRECTORY=${local.project_dir}",
    "JETBRAINS_JSON=${jsonencode(module.jetbrains_gateway)}",
    # "JETBRAINS_IDE_ID=${module.jetbrains_gateway.identifier != "" ? module.jetbrains_gateway.identifier : "NONE"}",
    # "JETBRAINS_IDE_NAME=${module.jetbrains_gateway.name != "" ? module.jetbrains_gateway.name : "NONE"}",
    # "JETBRAINS_IDE_VERSION=${module.jetbrains_gateway.version != "" ? module.jetbrains_gateway.version : "NONE"}",
    ]
}
```

The lines that are commented out, even without the fancy default setting, provide the following error.
```
Error: Unsupported attribute
on main.tf line 232, in resource "docker_container" "workspace":
  232:     "JETBRAINS_IDE_ID=${module.jetbrains_gateway.identifier != "" ? module.jetbrains_gateway.identifier : "NONE"}",
    ├────────────────
    │ module.jetbrains_gateway is a object
This object does not have an attribute named "identifier".
Error: Unsupported attribute
on main.tf line 233, in resource "docker_container" "workspace":
  233:     "JETBRAINS_IDE_NAME=${module.jetbrains_gateway.name != "" ? module.jetbrains_gateway.name : "NONE"}",
    ├────────────────
    │ module.jetbrains_gateway is a object
This object does not have an attribute named "name".
Error: Unsupported attribute
on main.tf line 234, in resource "docker_container" "workspace":
  234:     "JETBRAINS_IDE_VERSION=${module.jetbrains_gateway.version != "" ? module.jetbrains_gateway.version : "NONE"}",
    ├────────────────
    │ module.jetbrains_gateway is a object
This object does not have an attribute named "version".
```

The `JETBRAINS_JSON` env variable shows up as this, which seems to be an object of only a subset of data with the ID, Build #, and URL.
```json
{"jetbrains_ides":"[\"PY\",\"232.10203.26\",\"https://download.jetbrains.com/python/pycharm-professional-2023.2.4.tar.gz\"]"}
```

Ultimately, I want the ID as an ENV so that my personalize script can act upon which IDE is being utilized in the created workspace.
I would also like to show the IDE version as metadata.

**Comment by djarbz** [comment]
Interesting, I wonder if it works as the metadata as you have it because that can be compiled towards the end of the deployment. It may not work in my case because I am attempting to access it prior to the Docker deployment step?
However, that doesn't explain why I get the response that I did with the `jsonencode`.

I'll have to try a few things this evening.

**Comment by djarbz** [comment]
I don't specify a version in my config, I think in that case it just pulls the latest version?

**Comment by matifali** [comment]
@djarbz No. If you do not specify the `version`, it defaults to `v1.0.0`. 
As in my example above, you need to specify the `version` and update the `source`.

**Comment by matifali** [comment]
I am closing this as you are not on the latest version. Please comment again if you face this issue again on version 1.0.8

**Comment by djarbz** [comment]
Thanks for the help on this, everything is working now.
