### ISSUE TITLE
JetBrains-Gateway: Unable to connect via module

### ISSUE THREAD

**Issue by matifali** [coder/modules#189]
Coder version: `v2.9.0`

I am getting
```console
coder-jetbrains--main--gpu.matifali.dev: nodename nor servname provided, or not known
```

Connecting manually via the coder plugin works.

![image](https://github.com/coder/modules/assets/10648092/ad4e0074-2572-4d91-acd4-4a8b38cc1e57)

**Comment by matifali** [comment]
This seems to be broken after https://github.com/coder/jetbrains-coder/pull/372

**Comment by code-asher** [comment]
Can you confirm the version of the plugin?  This could actually be something we fixed in that PR, where it was using just the agent name instead of `workspace.agent`.

**Comment by matifali** [comment]
Ok So I was on `2.9.*`. Updating plugin to latest version fixed it.
