### ISSUE TITLE
VS Code Web: Add support for `settings`

### ISSUE THREAD

**Issue by michaelbrewer** [coder/modules#196]
Add support for pre-configuring settings with `vscode-web` like `code-server`

```terraform
module "vscode-web" {
  source     = "registry.coder.com/modules/vscode-web/coder"
  version    = "1.0.8"
  agent_id   = coder_agent.example.id
  extensions = ["dracula-theme.theme-dracula"]
  settings = {
    "workbench.colorTheme" = "Dracula"
  }
  accept_license = true
}
```

**Comment by matifali** [comment]
Let us @code-asher's views on what's the difference between User and Machine settings and which one should we use.

**Comment by michaelbrewer** [comment]
When i saved to `User` it would not take effect on `vscode-web`, i think they want you to use a github account for syncing settings or it stores it in the browser application data?

Only `Machine` would actually update.

**Comment by code-asher** [comment]
Oh sorry, this is VS Code web, not code-server!

Yes, you are right, upstream's web version only reads browser storage for user settings, it does *not* read `User` settings on the disk.  (We patch this in code-server so it reads from the disk.)

So yes, `Machine` is the only option there.

**Comment by matifali** [comment]
> `User` might be safer, as there are some settings that cannot be applied through `Machine`.
> 
> > Only Machine would actually update.
> 
> Are there settings that only work in `Machine` but not `User`? I thought it was the other way around.
> 
> I think maybe we could just expose both and let the template author decide where to put them. `settings.user` and `settings.machine` maybe.

wxposing both `settings.user` and `settings.machine` is a great idea for another PR. Could be added to code-server too.
