### ISSUE TITLE
Dotfiles: Execute Commands after Sync

### ISSUE THREAD

**Issue by djarbz** [coder/modules#199]
As a workaround to the module run order issue, I would like to request an option to specify a command that should be ran once the Dotfiles repo has been fully synced.

In my case, I would pass my `personalize.sh` script.
It may be useful to accept an array of commands, but I don't need that for my use case.

**Comment by matifali** [comment]
This could be a workaround, but IMO exceeds the scope of the module.
What do you think @mafredi?

**Comment by djarbz** [comment]
Alternatively, the personalize module could wait `$TIMEOUT` seconds for a script to appear?

**Comment by matifali** [comment]
Let us wait for @mafredri's comments

**Comment by djarbz** [comment]
Ahh, I was not aware of that!

setup.sh will work for my needs and I will no longer need the `personalize` module.
Thanks!

**Comment by mafredri** [comment]
I'm glad that was helpful @djarbz, in fact, there's many options to choose from with regards to file naming (not just `setup.sh`, see https://coder.com/docs/v2/latest/dotfiles#setup-script-support for the full list.
