### ISSUE TITLE
JetBrains Gateway

### ISSUE THREAD

**Issue by bpmct** [coder/modules#2]
## Must have

- [x] coder_app to open workspace in Gateway (https://github.com/coder/jetbrains-coder/pull/289)

## Should have 

- [x] Variables/icons for various IDEs 

@matifali feel free to expand

**Comment by matifali** [comment]
Ok. But aren't w adding a [native jetbarins app](https://github.com/coder/coder/issues/9679) similar to VSCode desktop?

**Comment by bpmct** [comment]
The plan is to actually abstract all helper apps to modules so a template is super prescriptive. Including VS Code and SSH

This will likely involve adding functionality to `coder_app`, so making a gateway one is a good exercise.

**Comment by matifali** [comment]
We should have a way to not leave a black window behind for external `coder_app`s.
