### ISSUE TITLE
Integrate Cursor.sh as an IDE Option in Coder

### ISSUE THREAD

**Issue by arnoldmukisa** [coder/modules#215]
I propose integrating cursor.sh as an IDE option alongside VSCode in Coder. Cursor.sh, being an AI-first fork of VSCode, offers unique features that could significantly benefit Coder's users, enhancing productivity and leveraging AI advancements in coding.

**Comment by bpmct** [comment]
Transferred this to our coder/modules repo :)

**Comment by stirby** [comment]
I plan to take a stab.

**Comment by ammario** [comment]
@stirby — status update?

**Comment by matifali** [comment]
@ammario It is done and available at https://regsitry.coder.com/modules/cursor
Sorry forgot to close the issue.
It was done in #290
