### ISSUE TITLE
JFrog Module

### ISSUE THREAD

**Issue by bpmct** [coder/modules#23]
Install and authenticate the JFrog CLI using the user's email!

**Comment by matifali** [comment]
I contributed to the Jfrog template. If it only requires configuring package managers and jfrog extension. I can do that too.

**Comment by bpmct** [comment]
actually, @ammario - can you take this since you're doing the demo of jfrog?

**Comment by matifali** [comment]
@bpmct Is anyone taking this, Or we can remove this from the list for the launch?
