### ISSUE TITLE
Web RDP module with devolutions-gateway

### ISSUE THREAD

**Issue by bpmct** [coder/modules#234]
I have validated a web RDP client called [devolutions-gateway](https://github.com/Devolutions/devolutions-gateway) which works well inside coder workspaces as a coder_app. See [RFC](https://www.notion.so/coderhq/Windows-Workspaces-Enablement-Package-18fdd9f4bfd84e6ea1e6fbb3898919a0)

![Screenshot 2024-04-23 at 10 57 09 AM](https://github.com/coder/modules/assets/22407953/717668e6-19fa-475f-b0a2-016278523d95)

You can see the WIP here: https://github.com/coder/modules/tree/web-rdp/windows-rdp. You can also try it in dogfood: https://dev.coder.com/templates/windows-with-good-rdp

However, the web app for the client itself requires a "log in," which in Coder's case is not necessary because the template can run the app in loopback and the Coder workspace proxy serves as the authentication mechanism (similar to how we pass `auth=none` to code-server). As far as I could tell, there is no way to hardcode credentials or pass them via a URL parameter. There is a way to pass a [custom static site](https://github.com/Devolutions/devolutions-gateway/blob/a884cbb8ff313496fb3d4072e67ef75350c40c03/devolutions-gateway/tests/config.rs#L271) so that we do not need to fork gateway itself.

[WebRDP module](https://github.com/coder/modules/tree/web-rdp/windows-rdp)
[Angular component](https://github.com/Devolutions/devolutions-gateway/tree/master/webapp) of [Devolutions Gateway](https://github.com/Devolutions/devolutions-gateway/tree/master)
[WebRDP Dogfood Template](https://dev.coder.com/templates/windows-with-good-rdp)

## Must have

- [x] When a user clicks the app, they do not have to log in via the devolutions gateway form. Instead, they are taken directly to the desktop (or coder admin log in)
  - We could do this several ways, as far as I can tell:
    - building our own web app and passing it to devolutions gateway [(link)](https://github.com/Devolutions/devolutions-gateway/blob/a884cbb8ff313496fb3d4072e67ef75350c40c03/devolutions-gateway/tests/config.rs#L271)
    - forking devolutions-gateway and modifying `webapp/` dir
    - building our own project that consumes the same devolutions gateway dependencies (ironRDP webcomponents)
  - Curious for other people's thoughts, but my preference is we do it in a way where we can upstream the changes to devolutions gateway :) I'm sure they would want to support auto log in via a config value or something

## Should have

- [x] We hide the sidebar once somebody logs in so the RDP session takes up the whole screen
- [ ] We hide the top action bar once somebody logs in so the RDP session takes up the whole screen

## Nice to have

- [ ] Resizing sometimes doesn't work until you refresh, ideally we can investigate/fix this too :)

**Comment by michaelbrewer** [comment]
Very cool. Would like to see how to run this within a kubernetes cluster too.

**Comment by bpmct** [comment]
Sadly, Windows containers do not support a desktop environment as far as I can tell. I think VMs are the only route, but something like Kubevirt could be used to manage VMs via the Kubernetes API.

**Comment by bpmct** [comment]
We also need to test this on AWS and Azure before merging and edit the README

**Comment by Kira-Pilot** [comment]
Kirby to reach out to Ben regarding release timing and Azure support.

**Comment by Kira-Pilot** [comment]
We'll want to follow-up with an internal note in this ticket when this is released: https://coder.zendesk.com/agent/tickets/2927
