### ISSUE TITLE
coder-login module page is 404

### ISSUE THREAD

**Issue by evilhamsterman** [coder/modules#257]
Simple as the description says, the page for the coder-login module https://registry.coder.com/modules/coder-login just returns a 404 

![image](https://github.com/coder/modules/assets/59560/612a45f2-f1f9-4c59-a622-cb45134d1f83)

**Comment by matifali** [comment]
cc: @stirby

**Comment by matifali** [comment]
Seems to work now.

**Comment by matifali** [comment]
@kylecarbs, we should investigate why it was a 404.
