### ISSUE TITLE
Filebrowser module: support for subdomain = false

### ISSUE THREAD

**Issue by Seppdo** [coder/modules#285]
The Filebrowser can be configured to use a different baseURL than / with the command line parameter -b / --baseurl.

This can be used to allow using subdomain = false like in the terminal or code-server module.

**Comment by matifali** [comment]
We would be happy to get a PR. Are you interested in contributing this functionality?

**Comment by Seppdo** [comment]
> We would be happy to get a PR. Are you interested in contributing this functionality?

I will take a look at it and contribute the results if they are appropriate for distribution.
