### ISSUE TITLE
README template for modules

### ISSUE THREAD

**Issue by bpmct** [coder/modules#3]
Create a general template for modules. This will probably require some ideation as we add several. This is just a dump of some initial ideas, but we can consider this issue closed when we are happy with a template that works across 5-10 modules.

- [ ] Requirements and prerequisites for module (e.g. OS, architecture)
- [ ] Frontmatter with tags (e.g. `ide`)
- [ ] Screenshots section or GIF demo
- [ ] Compatible templates?

**Comment by matifali** [comment]
Compatible templates should be in frontmatter so that we can extract them and use as filters on coder template registry

**Comment by bpmct** [comment]
Agreed.

**Comment by bpmct** [comment]
@matifali should we close this in favor of #29

**Comment by matifali** [comment]
closing in favour of #29
