### ISSUE TITLE
Failed to retrieve available versions

### ISSUE THREAD

**Issue by pxPP** [coder/modules#306]
Currently its not possible to fetch avialable Version, so our workspaces cannot start:

`Error: Error accessing remote module registry
  on project.tf line 81:
  81: module "git-clone" {
Failed to retrieve available versions for module "git-clone"
(project.tf:81) from registry.coder.com: the request failed after 2
attempts, please try again later: 500 Internal Server Error returned from
https://registry.coder.com/api/modules/v1/modules/git-clone/coder/versions.`

The version Api returned a `{
  "error": "Failed to fetch tags."
}`

**Comment by GilQedma** [comment]
I encountered the issue within the last hour as well, but it seems the API is now functioning again 🚀

**Comment by matifali** [comment]
This has been resolved and should be up and running now. Thank you for reporting and your patience.
