### ISSUE TITLE
Add screenshots to modules

### ISSUE THREAD

**Issue by bpmct** [coder/modules#32]
The following READMEs could benefit from screenshots

- [ ] VS Code Web (with copilot or live share in browser)
- [ ] AWS Regions
- [ ] Azure Regions
- [ ] kasmVNC
- [ ] Juypyter
- [ ] GCP Region
- [ ] Fly Region
- [ ] JFrog
- [ ] Personalize
- [ ] VS Code Desktop

**Comment by matifali** [comment]
Closing in favour of #35
