### ISSUE TITLE
Temporary breakage of registry due to version mismatches

### ISSUE THREAD

**Issue by jeehoonkang** [coder/modules#324]
I'm trying to use the new version of the filebrowser module per this PR: https://github.com/coder/modules/pull/320

The registry website (https://registry.coder.com/modules/filebrowser) currently says I can use version 1.0.22.
Though it seems I cannot because the new version is not released yet: https://github.com/coder/modules/releases

I believe the registry website's version should work.
I'm not asking for all updates to be released right away.
I'm just asking that the registry website should be updated at the same time that a new version is released.

**Comment by matifali** [comment]
@bcpeinhardt this is because we render registry.coder.com from `main`. Can you please change it to use the latest published tag instead?

**Comment by bcpeinhardt** [comment]
As a temporary fix I have published a new tag v1.0.22. The website should update within an hour.
