### ISSUE TITLE
File Browser Icon is not showing / Heading Over write

### ISSUE THREAD

**Issue by Ajithpalotte** [coder/modules#374]
Referring the issue #372 

Hello @matifali,

I am using the filebrowser module with version version = "1.0.25" after updating the version 2.17 i am getting the below error.

  | Create one by running  terraform init  in your template directory.
=== ✔ Queued [81ms]
==> ⧗ Running
==> ⧗ Running
=== ✔ Running [18ms]
==> ⧗ Setting up
=== ✔ Setting up [0ms]
==> ⧗ Parsing template parameters
=== ✔ Parsing template parameters [25ms]
==> ⧗ Detecting persistent resources
2024-12-19 14:18:47.657+05:30 Error: Unresolvable module version constraint
2024-12-19 14:18:47.657+05:30   on main.tf line 195:
2024-12-19 14:18:47.657+05:30  195: module "filebrowser" {
2024-12-19 14:18:47.657+05:30 There is no available version of module
2024-12-19 14:18:47.657+05:30 "registry.coder.com/modules/filebrowser/coder" (main.tf:195) which matches
2024-12-19 14:18:47.657+05:30 **the given version constraint. The newest available version is 1.0.25.**
=== ✔ Detecting persistent resources [834ms]
==> ⧗ Cleaning Up
=== ✘ Cleaning Up [21ms]
=== ✘ Cleaning Up [212ms]
I am using the below code

module "filebrowser" {
  count    = data.coder_workspace.me.start_count
  source   = "registry.coder.com/modules/filebrowser/coder"
  version  = "1.0.25"
  agent_id = coder_agent.dev[0].id
  port     = local.filebrowser_port
  slug     = "filebrowser"
  folder   = "/home/coder/"
  share    = "owner"

}

**Comment by matifali** [comment]
I am unable to reproduce with your provided snippet on v2.17,3 of Coder. Could you please share your full `main.tf` file or a minimum reproduction?

**Comment by Ajithpalotte** [comment]
Hello @mafredri ,

main file attached.
[main.txt](https://github.com/user-attachments/files/18196075/main.txt)

**Comment by matifali** [comment]
You should update Coder to version 2.17.3 or above and use version 1.0.25 for module.
I see you are using 2.17 in the module.

**Comment by matifali** [comment]
Please comment if you are still facing the issue.

```tf
module "filebrowser" {
	count    = data.coder_workspace.me.start_count
	source   = "registry.coder.com/modules/filebrowser/coder"
	version  = "1.0.25" # version should be 1.0.25 and not 2.17 as you did in your shared `main.tf`
	agent_id = coder_agent.dev[0].id
	port     = local.filebrowser_port
	folder   = "/home/coder/"
}
```
