### ISSUE TITLE
Azure regions City names

### ISSUE THREAD

**Issue by matifali** [coder/modules#38]
Use city names for each region, like GCP and AWS regions modules.

<img width="322" alt="Screenshot 2023-09-24 at 16 54 29" src="https://github.com/coder/modules/assets/10648092/9bd9e37d-8b1b-4f49-8f1c-bedb7cf6968f">
many of the regions do not list city names.

It would be nice if we can list city names for each region. e.g.,
1. Europe (France)
2. Europe (Netherlands)
3. Australia (Sydney)
4. Australia (Melbourne)

Reference:
https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies

**Comment by stirby** [comment]
Thank you for bringing this up, fixing it now.

**Comment by stirby** [comment]
@matifali Not every region has an associated city based on these two resources.
- [Azure Tracks](https://azuretracks.com/2021/04/current-azure-region-names-reference/)
- [gist](https://gist.github.com/ausfestivus/04e55c7d80229069bf3bc75870630ec8)

Would it be better to only include those with a city listed on the link you provided?

**Comment by matifali** [comment]
@stirby As per https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#choose-your-region
East US and East US2 is Virginia, while East US 3 is Georgia

Thoughts on adding the states at least?

**Comment by stirby** [comment]
I'll add all the states/provinces listed here.

**Comment by stirby** [comment]
@matifali I've just checked all the regions listed on that resource and the corresponding states/provinces are listed. This includes the EastUS regions you mentioned. The only way I see to remedy this is by removing the less descriptive regions.

**Comment by matifali** [comment]
@stirby, let us leave this. I guess it is not worth the effort. Thanks for looking into this.
