### ISSUE TITLE
add end-2-end tests for modules

### ISSUE THREAD

**Issue by matifali** [coder/modules#65]
- [ ] Test coder_parameter with and without default
- [ ] Test all example cases
- [ ] Test coder_script based modules
- [ ] Test if coder_apps are healthy and accessible.

We can have a test deployment for testing modules and use ci to create and update templates using modules and test using a workspace.

**Comment by bpmct** [comment]
I don't have strong opinions on whether we should e2e test our modules versus. I think e2e testing our example templates is a good way to avoid bugs in our most critical modules and then #55 can at least ensure that a template isn't randomly updated to a module that is broken.
