### ISSUE TITLE
Ensure that not setting default or setting default to "" or `null` sets the default to `null` for all coder_parameter modules 

### ISSUE THREAD

**Issue by matifali** [coder/modules#66]
While testing I noticed that

- [ ] JetBrains Gateway module fails if no default is set.
- [x] Azure regions module sets the default region to `eastus` if no default is set.
- [x] AWS regions module sets the default region to `us-east-1` if no default is set. 

Ideal behavior should be that setting the default to `null` should set the default of `coder_paramter` to `null` so that the user is forced to choose a value from the list.

**Comment by stirby** [comment]
I notice when the default is `null` on a coder_parameter, the create workspace page reloads when no option is selected rather than throwing an error message. Is this the expected behavior?

**Comment by matifali** [comment]
@stirby for parameters that have options when the default is `null`, it should ask the user to choose one of the options.

**Comment by stirby** [comment]
Please see PR #72 for approval of `jetbrains-gateway` implementation.
