### ISSUE TITLE
create a  coder-login module

### ISSUE THREAD

**Issue by matifali** [coder/modules#67]
A module that can automatically login a user to coder deployment inside a workspace.
We have a nice workaround [here](https://github.com/coder/coder/blob/87ebe6c2c2387b4249ba959616cf8a0b73684cbd/dogfood/main.tf#L215-L221)

```shell
# Automatically authenticate the user if they are not already logged in
if ! coder list >/dev/null 2>&1; then
  set +x; coder login --token=$CODER_USER_TOKEN --url=$CODER_DEPLOYMENT_URL
else
  echo "You are already authenticated with Coder"
fi
```

**Comment by stirby** [comment]
I'll work on setting it up today.
