### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by bpmct** [coder/modules#7]
`git clone` module to detect if repo exists and clone it

## Nice to have

- [ ] Support forking instead of clone with `gh` CLI (we could support other clouds down the road).

**Comment by matifali** [comment]
Feel free to skip forking if it takes time. We can add that later, maybe.

**Comment by matifali** [comment]
closed in #46

**Comment by Gaming4LifeDE** [comment]
How are you supposed to deal with host key verification errors when using ssh clone URL's? The script doesn't implement a way to add the host key (ssh-keyscan, etc...)

**Comment by matifali** [comment]
The assumption is that a coder workspace is pre authenticated with GitHub with an OIDC token.

**Comment by Gaming4LifeDE** [comment]
The idea is good. Problem is that I'm trying to authenticate against a private gitlab instance

**Comment by matifali** [comment]
You should be able to configure GitLab private instance as an [external auth provider](https://coder.com/docs/v2/latest/admin/external-auth#git-providers) using the following docs
https://docs.gitlab.com/ee/integration/oauth_provider.html
