### ISSUE TITLE
Update Documentation on parameter name changes

### ISSUE THREAD

**Issue by djarbz** [coder/modules#74]
This parameter changed names and is no longer matching as per the [documentation](https://registry.coder.com/modules/jetbrains-gateway).

https://github.com/coder/modules/blob/9f110e6e63e51942a45bb2c88931420c650e4026/jetbrains-gateway/main.tf#L22-L25

**Comment by stirby** [comment]
Hey @djarbz, thanks for raising this issue. The registry documentation was not syncing to GitHub, but should now update every ten minutes.

Thanks @kylecarbs for the fix.

**Comment by djarbz** [comment]
Excellent, thank you!

I appreciate your team's work on providing this registry BTW, very helpful.
I'm working on a template that I'm hoping, after some internal testing, I can submit to be included.

**Comment by djarbz** [comment]
@stirby I'm not sure this is fixed, I see you pushed a fix for my Filebrowser DB issue, but it is not live on the registry site yet.
